steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/furniture-backend', './backend']
  
  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/furniture-frontend', './frontend']
  
  # Push Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/furniture-backend']
  
  # Push Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/furniture-frontend']
  
  # Deploy Backend Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'furniture-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/furniture-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--set-secrets'
      - 'REDIS_URL=redis-url:latest'
      - '--update-env-vars'
      - 'PROJECT_ID=$PROJECT_ID'
  
  # Deploy Frontend Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'furniture-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/furniture-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'VITE_API_URL=https://furniture-backend-${_LOCATION_ID}.a.run.app'

substitutions:
  _LOCATION_ID: 'us-central1'

images:
  - 'gcr.io/$PROJECT_ID/furniture-backend'
  - 'gcr.io/$PROJECT_ID/furniture-frontend' 